### ISSUE TITLE
v0.1.6 crashes on install (v0.1.5 was working fine)

### ISSUE THREAD

**Issue by gruijter** [jordenc/io.nuki.smartlock#6]
app.js init done
SyntaxError: Unexpected token var
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /homey-app/manager/drivers.js:74:27
    at Array.forEach (native)
    at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)

--- INFO: io.nuki.smartlock has been killed ---

**Comment by chrisboer** [comment]
No issues should work perfectly

**Comment by jordenc** [comment]
I assume this is fixed already (somehow I don't get notifications of tickets, sorry)
